stages:
- stage: Deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool: test
    # creates an environment if it doesn't exist
    environment: test4
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
